### PR TITLE
Adds youtube videoId for 0x staking explainer video

### PR DESCRIPTION
**Pull request by johnrjj**

### CODE REVIEW

**Comment by chriskalani** [comment]
This looks like the full ZRX video. We planned on linking to a shorter video that covers just ZRX staking. I'll ping Matt for the shorter video ID.

**Comment by johnrjj** [comment]
> This looks like the full ZRX video. We planned on linking to a shorter video that covers just ZRX staking. I'll ping Matt for the shorter video ID.

Sounds good

**Comment by johnrjj** [comment]
@chriskalani -- Matt gave me the start time (via Asana), I went ahead and added that.

**Review by kimpers — APPROVED** [review]

**Comment by johnrjj** [comment]
I'm going to do the video cover image in a separate PR.

**Pull request merged**
