### PR TITLE
Add wCELO balances in /treasury page (fixes 0xProject/website#429)

### PR DESCRIPTION
**Pull request by vjnrv**
Added wCELO balances in Governance and  Treasury pages.

### CODE REVIEW

**Comment by mintcloud** [comment]
hey @vjnrv just testing this locally and while I see Celo appearing, the USD value doesn't seem to be populating correctly (shows 0 USD)

https://pasteboard.co/dXSmMWKXkV7H.png

**Comment by vjnrv** [comment]
Hi @mintcloud! 

This appears to be a behavior of the `formatNumber` function, it doesn't show values less than $10.

https://github.com/0xProject/website/blob/development/ts/utils/format_number.ts#L230

**Review by kimpers — APPROVED** [review]
Awesome work! I'll merge and get this deployed asap 🎉

**Comment by mintcloud** [comment]
thanks @vjnrv for shipping this, mind messaging me (mintcloud#8529) or nikita (nikita#4377) on Discord to arrange the payout of the bounty? Thanks again!

**Comment by vjnrv** [comment]
Hey @mintcloud. I've sent friendship request from Jota#7213 for you and nikita.

**Pull request merged**
